// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/jwt.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/jwt.go -destination=internal/auth/mock/jwt.go -package mock JWTAuthentication
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	auth "github.com/rovany706/url-shortener/internal/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTAuthentication is a mock of JWTAuthentication interface.
type MockJWTAuthentication struct {
	ctrl     *gomock.Controller
	recorder *MockJWTAuthenticationMockRecorder
	isgomock struct{}
}

// MockJWTAuthenticationMockRecorder is the mock recorder for MockJWTAuthentication.
type MockJWTAuthenticationMockRecorder struct {
	mock *MockJWTAuthentication
}

// NewMockJWTAuthentication creates a new mock instance.
func NewMockJWTAuthentication(ctrl *gomock.Controller) *MockJWTAuthentication {
	mock := &MockJWTAuthentication{ctrl: ctrl}
	mock.recorder = &MockJWTAuthenticationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTAuthentication) EXPECT() *MockJWTAuthenticationMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockJWTAuthentication) CreateToken(userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockJWTAuthenticationMockRecorder) CreateToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockJWTAuthentication)(nil).CreateToken), userID)
}

// GetClaimsFromToken mocks base method.
func (m *MockJWTAuthentication) GetClaimsFromToken(tokenString string) (*auth.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClaimsFromToken", tokenString)
	ret0, _ := ret[0].(*auth.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClaimsFromToken indicates an expected call of GetClaimsFromToken.
func (mr *MockJWTAuthenticationMockRecorder) GetClaimsFromToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClaimsFromToken", reflect.TypeOf((*MockJWTAuthentication)(nil).GetClaimsFromToken), tokenString)
}
