services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: "shortenerdb"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "example" # change in production
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata:z # needs :z to work with selinux
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d shortenerdb" ]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true

volumes:
  pgdata:
    driver: local
