// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/database.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/database.go -destination=internal/database/mock/database.go -package mock Database
//

// Package mock is a generated GoMock package.
package mock
